ALTER TABLE CLIENTES ADD N_TITULOS COMPUTED BY  ((SELECT COUNT(BOLETO_ID) FROM BOLETOS WHERE CLI_ID = CLIENTES.CLI_ID AND BOLETOS.SITUACAO_BOLETO=('A RECEBER') and CLIENTES.SIT=1 and CLIENTES.TIPO='001 - Escola' ));

